### ISSUE TITLE
Read Repeatedly

### ISSUE THREAD

**Issue by truehang** [rezabrizi/SPMC-Queue#1]
After reading your code, I found that multiple consumers will read the same data repeatedly. If we stipulate that a piece of data can only be read once, how should we improve it? Make the read index atomic?

**Comment by rezabrizi** [comment]
Hey,

The way I have it implemented right now is as a multi consumer, multi read queue.

This can easily be changed (not necessarily improved) to allow for only one read. In fact that’s the original version I came up with.

Here is how to do it, instead of doing a +2 to the version after reading, do a +1 or set to 0 (point is you want the version to be even to indicate no more reads allowed). The difference between +1 or 0:

  *   If you do +1 then you can find number of rewrites by the writer by diving the version number by 2 and then rounding up.
  *   If you do set to 0 then you lose number of rewrites.

Either way, you will only have one read per piece of data.

Best,
Reza
________________________________
From: truehang ***@***.***>
Sent: Wednesday, October 23, 2024 9:40:29 PM
To: rezabrizi/SPMC-Queue ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rezabrizi/SPMC-Queue] Read Repeatedly (Issue #1)


After reading your code, I found that multiple consumers will read the same data repeatedly. If we stipulate that a piece of data can only be read once, how should we improve it? Make the read index atomic?

**Comment by truehang** [comment]
Thank you very much for your detailed reply. It turns out that the change to support read once and read multiple times is so simple. In my implementation, I also added an atomic variable to indicate whether it was read or not, which now seems completely unnecessary.

**Comment by truehang** [comment]
>           // Perform the read
            std::memcpy(data, block.mData, size);
            // Indicate that a read has occurred by adding a 2 to the version
            // However do not block subsequent reads
            block.mVersion.store(version + 2, std::memory_order_release);

I checked your code and found that your method cannot guarantee that the data will be read only once, because you change the value of version after getting the data, which means that multiple readers can get the value, but only one of them changes the value of version. I am trying to find a solution...

**Comment by truehang** [comment]
After further testing the code, I found that adding an unread atomic variable can greatly improve performance because the new atomic variable reduces the competition for the original version atomic variable. The code is roughly as follows:

>struct Header
{
    std::atomic<uint64_t> m_block_counter {0};
    // read index
    std::atomic<uint64_t> m_read_idx {0};
};

    void write(...){
     ...
        // update data
        c(block.mData);
        block.m_unread.store(true);
        block.m_version.store(currentVersion, std::memory_order_release);
    }


    bool read (...) const {
     ...
        if(version % 2 == 1){
          // ensure the data is unread
          if (block.m_unread.load()) {
           // access the data
            if (block.m_unread.exchange(false)) {
              // Perform the read
            std::memcpy(data, block.mData, size);
              return true;
            }
          }
        }
        ...
    }

**Comment by truehang** [comment]
I think my implementation is pretty good, if you have a better idea, you are welcome to provide it.
